### ISSUE TITLE
이 스터디에서는 GitHub의 다양한 기능을 적극 활용하고자 합니다.

### ISSUE THREAD

**Issue by akaiuun12** [akaiuun12/yonsei-psych-python#1]
안녕하세요. 

오프라인이 아닌 온라인으로 스터디를 진행하려니 어려움이 많네요. 
기본적으로 강의 형식이 아니라 모두가 상호작용하는 스터디가 낫다고 생각해요.

그걸 구현하는 방법이 여러가지가 있겠지만 모두가 쉽게 쓸 수 있는 GitHub를 골랐습니다. 
하지만 GitHub가 생소한 사람들도 있을거예요. 저도 사실 생소해요.. 
하나씩 Git과 GitHub 사용법을 배웠으면 좋겠습니다. 

일단 **이 이슈에 자기를 소개하는 짧은 댓글을 남겨주세요.**

**Comment by georgesilver33** [comment]
네 좋습니다!

**Comment by sis01245** [comment]
홍민석입니다.

**Comment by injaehong** [comment]
안녕하세요, 인지랩 홍인재입니다 :-) 깃허브라니 이도준 선생님 제자다워요! 멋져요!

**Comment by JinhyeokJeong** [comment]
안녕하세요. VCC 연구실 정진혁입니다. GitHub를 한번 써보고 싶었는데 계기가 없어 시작을 못하고 있었는데, 이 참에 써봐야겠네요 ㅎㅎ

**Comment by JeunghwanChoi** [comment]
안녕하세요! VCC 최정환입니다!
